"""
tool_registry.py — Master AI Tool Registry for ClipAI Studio
============================================================
Single source of truth for all 212 AI-controllable features.
Each tool has: name, description, parameters schema, category, side effects, confirmation required.

Used by:
  - orchestrator.py (for LLM function-calling)
  - gemma_multimodal.py (for AI Director)
  - api.py (for /api/ai/tools endpoint)
  - CopilotChat.tsx (for confirmation flow)
"""

from typing import Dict, List, Any, Optional


# ─────────────────────────────────────────────────────────────────────────────
# Tool Schema Types
# ─────────────────────────────────────────────────────────────────────────────

TOOL_CATEGORIES = {
    "timeline":   "Timeline & Editing (40 tools)",
    "playback":   "Player & Playback (25 tools)",
    "effects":    "Effects & Color Grading (30 tools)",
    "audio":      "Audio Production (25 tools)",
    "subtitles":  "Subtitles & Captions (22 tools)",
    "ai":         "AI & ML (45 tools)",
    "export":     "Export & Sharing (25 tools)",
}


# ─────────────────────────────────────────────────────────────────────────────
# TOOL_REGISTRY — 212 entries
# ─────────────────────────────────────────────────────────────────────────────

TOOL_REGISTRY: Dict[str, Dict[str, Any]] = {
    # ════════════════════════════════════════════════════════════════════
    # 1. TIMELINE & EDITING (40 tools)
    # ════════════════════════════════════════════════════════════════════
    "timeline.split_clip": {
        "description": "Split a clip at the playhead or specified time into two clips",
        "description_ar": "قسّم كليب عند البلاي هيد أو وقت محدد لكليبين",
        "category": "timeline",
        "params": {"clip_id": "string", "time": "float (seconds)"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.ripple_delete": {
        "description": "Delete a clip and close the gap automatically",
        "description_ar": "احذف كليب وسد الفجوة تلقائياً",
        "category": "timeline",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "timeline.delete_clip": {
        "description": "Delete a clip from the timeline (with optional confirmation prompt)",
        "description_ar": "احذف كليب من التايملاين",
        "category": "timeline",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "timeline.insert_edit": {
        "description": "Switch to Insert edit mode (clips push later)",
        "description_ar": "فعّل وضع Insert (الكليبات بتتزحلق لقدام)",
        "category": "timeline",
        "params": {},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.overwrite_edit": {
        "description": "Switch to Overwrite edit mode (clips replace existing)",
        "description_ar": "فعّل وضع Overwrite (الكليبات الجديدة بتستبدل)",
        "category": "timeline",
        "params": {},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.toggle_magnetic": {
        "description": "Toggle magnetic timeline (auto-snap to neighbors)",
        "description_ar": "فعّل الـ Magnetic timeline (سناب تلقائي)",
        "category": "timeline",
        "params": {"enabled": "boolean"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.set_snap_mode": {
        "description": "Set snapping mode (off/playhead/clips/grid)",
        "description_ar": "حدد وضع السناب (إيقاف/بلاي هيد/كليبات/جريد)",
        "category": "timeline",
        "params": {"mode": "string (off|playhead|clips|grid)"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.zoom_to_fit": {
        "description": "Zoom timeline to show all clips",
        "description_ar": "زوّم التايملاين عشان يبان كله",
        "category": "timeline",
        "params": {},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.set_zoom_level": {
        "description": "Set timeline zoom (pixels per second)",
        "description_ar": "حدد زووم التايملاين (بكسل/ثانية)",
        "category": "timeline",
        "params": {"pixels_per_second": "float (5-120)"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.set_in_point": {
        "description": "Set In point at playhead (I key)",
        "description_ar": "حدد نقطة In عند البلاي هيد (مفتاح I)",
        "category": "timeline",
        "params": {"time": "float (seconds)"},
        "side_effects": ["work_area"],
        "requires_confirmation": False,
    },
    "timeline.set_out_point": {
        "description": "Set Out point at playhead (O key)",
        "description_ar": "حدد نقطة Out عند البلاي هيد (مفتاح O)",
        "category": "timeline",
        "params": {"time": "float (seconds)"},
        "side_effects": ["work_area"],
        "requires_confirmation": False,
    },
    "timeline.render_preview_region": {
        "description": "Render preview for In/Out region only",
        "description_ar": "اعمل رندر لمنطقة In/Out بس",
        "category": "timeline",
        "params": {"resolution": "string (full|half|quarter)"},
        "side_effects": ["render_cache"],
        "requires_confirmation": False,
    },
    "timeline.lock_track": {
        "description": "Lock a track to prevent editing",
        "description_ar": "اقفل تراك عشان ميقدرش يتعدّل",
        "category": "timeline",
        "params": {"track_id": "string", "locked": "boolean"},
        "side_effects": ["track_state"],
        "requires_confirmation": False,
    },
    "timeline.hide_track": {
        "description": "Hide a track from preview",
        "description_ar": "اخفي تراك من المعاينة",
        "category": "timeline",
        "params": {"track_id": "string", "hidden": "boolean"},
        "side_effects": ["track_state"],
        "requires_confirmation": False,
    },
    "timeline.solo_track": {
        "description": "Solo a track (mute all others)",
        "description_ar": "اعمل solo لتراك (اكتم الباقي)",
        "category": "timeline",
        "params": {"track_id": "string", "soloed": "boolean"},
        "side_effects": ["track_state"],
        "requires_confirmation": False,
    },
    "timeline.reorder_tracks": {
        "description": "Reorder tracks in the timeline",
        "description_ar": "أعد ترتيب التراكات في التايملاين",
        "category": "timeline",
        "params": {"track_id": "string", "new_index": "integer"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.rename_track": {
        "description": "Rename a track",
        "description_ar": "غيّر اسم تراك",
        "category": "timeline",
        "params": {"track_id": "string", "name": "string"},
        "side_effects": ["track_state"],
        "requires_confirmation": False,
    },
    "timeline.mark_in_out": {
        "description": "Mark In/Out points around the playhead and extract subclip",
        "description_ar": "حدد In/Out حوالين البلاي هيد واستخرج كليب فرعي",
        "category": "timeline",
        "params": {"in_time": "float", "out_time": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.replace_clip": {
        "description": "Replace clip source while keeping attributes",
        "description_ar": "استبدل مصدر الكليب مع الحفاظ على الـ attributes",
        "category": "timeline",
        "params": {"clip_id": "string", "new_source_path": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "timeline.slip_clip": {
        "description": "Slip clip (change in/out together, keep duration)",
        "description_ar": "اعمل Slip (غيّر in/out مع بعض، نفس الطول)",
        "category": "timeline",
        "params": {"clip_id": "string", "delta_seconds": "float"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.slide_clip": {
        "description": "Slide clip between its neighbors",
        "description_ar": "اعمل Slide (حرّك كليب بين جيرانه)",
        "category": "timeline",
        "params": {"clip_id": "string", "delta_seconds": "float"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.razor_at_playhead": {
        "description": "Cut all clips at the playhead (Ctrl+K)",
        "description_ar": "اقطع كل الكليبات عند البلاي هيد (Ctrl+K)",
        "category": "timeline",
        "params": {},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.three_point_edit": {
        "description": "3-point edit (in/out + target duration)",
        "description_ar": "مونتاج 3 نقاط (in/out + الطول المطلوب)",
        "category": "timeline",
        "params": {"in_time": "float", "out_time": "float", "target_track_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.top_and_tail": {
        "description": "Remove first/last N seconds of a clip",
        "description_ar": "احذف أول/آخر N ثواني من كليب",
        "category": "timeline",
        "params": {"clip_id": "string", "head_seconds": "float", "tail_seconds": "float"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.lift_clip": {
        "description": "Lift clip out (leave gap)",
        "description_ar": "ارفع كليب (سيب فجوة)",
        "category": "timeline",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "timeline.extract_clip": {
        "description": "Extract clip and close gap",
        "description_ar": "استخرج كليب واقفل الفجوة",
        "category": "timeline",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "timeline.freeze_frame": {
        "description": "Freeze frame at playhead (extend last frame as image)",
        "description_ar": "ثبّت فريم عند البلاي هيد (زوّد آخر فريم كصورة)",
        "category": "timeline",
        "params": {"time": "float", "duration_seconds": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.time_remap": {
        "description": "Time remapping (variable speed via keyframes)",
        "description_ar": "Time remapping (سرعة متغيرة بـ keyframes)",
        "category": "timeline",
        "params": {"clip_id": "string", "keyframes": "array of {time, speed, easing}"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.reverse_clip": {
        "description": "Reverse a clip playback direction",
        "description_ar": "اعكس اتجاه تشغيل الكليب",
        "category": "timeline",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": False,
    },
    "timeline.sync_lock": {
        "description": "Enable sync lock between video and audio",
        "description_ar": "فعّل sync lock بين الفيديو والصوت",
        "category": "timeline",
        "params": {"track_id": "string", "enabled": "boolean"},
        "side_effects": ["track_state"],
        "requires_confirmation": False,
    },
    "timeline.linked_selection": {
        "description": "Enable linked selection (move audio with video)",
        "description_ar": "فعّل linked selection (الصوت بيمشي مع الفيديو)",
        "category": "timeline",
        "params": {"enabled": "boolean"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.fix_audio_drift": {
        "description": "Auto-correct audio drift between video and audio tracks",
        "description_ar": "صلّح drift الصوت تلقائياً بين الفيديو والصوت",
        "category": "timeline",
        "params": {"video_clip_id": "string", "audio_clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.group_clips": {
        "description": "Group multiple clips into one logical unit",
        "description_ar": "جمّع كليبات في وحدة منطقية واحدة",
        "category": "timeline",
        "params": {"clip_ids": "array of strings", "group_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.ungroup_clips": {
        "description": "Ungroup a clip group",
        "description_ar": "فكّ تجميع الكليبات",
        "category": "timeline",
        "params": {"group_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.create_nested_sequence": {
        "description": "Create nested sequence (composition of clips)",
        "description_ar": "اعمل sequence متداخل (تركيب من كليبات)",
        "category": "timeline",
        "params": {"name": "string", "clip_ids": "array of strings"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.add_adjustment_layer": {
        "description": "Add an adjustment layer (effects apply to all below)",
        "description_ar": "أضف adjustment layer (التأثيرات تطبق على الكل تحتها)",
        "category": "timeline",
        "params": {"track_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "timeline.add_marker": {
        "description": "Add a marker on the timeline (colored note)",
        "description_ar": "أضف marker على التايملاين (ملاحظة ملوّنة)",
        "category": "timeline",
        "params": {"time": "float", "color": "string", "name": "string", "comment": "string"},
        "side_effects": ["markers"],
        "requires_confirmation": False,
    },
    "timeline.add_chapter_marker": {
        "description": "Add a chapter marker (creates chapter index)",
        "description_ar": "أضف chapter marker (يولّد فهرس فصول)",
        "category": "timeline",
        "params": {"time": "float", "chapter_name": "string"},
        "side_effects": ["markers"],
        "requires_confirmation": False,
    },
    "timeline.set_region_of_interest": {
        "description": "Set a region of interest (highlighted timeline area)",
        "description_ar": "حدد منطقة اهتمام (منطقة مميّزة على التايملاين)",
        "category": "timeline",
        "params": {"start": "float", "end": "float", "color": "string"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "timeline.take_snapshot": {
        "description": "Take a frame snapshot (save to image file)",
        "description_ar": "التقط snapshot (احفظ فريم كصورة)",
        "category": "timeline",
        "params": {"time": "float", "output_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 2. PLAYBACK (25 tools)
    # ════════════════════════════════════════════════════════════════════
    "playback.play": {
        "description": "Start playback",
        "description_ar": "شغّل الفيديو",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.pause": {
        "description": "Pause playback",
        "description_ar": "وقّف الفيديو",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_play": {
        "description": "Toggle play/pause (Space)",
        "description_ar": "بدّل تشغيل/إيقاف (Space)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.seek": {
        "description": "Seek to specific time",
        "description_ar": "روح لوقت محدد",
        "category": "playback",
        "params": {"time": "float (seconds)"},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.frame_step_forward": {
        "description": "Step forward 1 frame (Right Arrow)",
        "description_ar": "تقدّم فريم (سهم يمين)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.frame_step_backward": {
        "description": "Step backward 1 frame (Left Arrow)",
        "description_ar": "ارجع فريم (سهم شمال)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.skip_forward_5s": {
        "description": "Skip forward 5 seconds (Shift+Right)",
        "description_ar": "تقدّم 5 ثواني (Shift+Right)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.skip_backward_5s": {
        "description": "Skip backward 5 seconds (Shift+Left)",
        "description_ar": "ارجع 5 ثواني (Shift+Left)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_loop": {
        "description": "Toggle loop playback (L key)",
        "description_ar": "بدّل loop (مفتاح L)",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.jog_mode": {
        "description": "Enter jog/shuttle mode for frame-accurate scrubbing",
        "description_ar": "ادخل وضع jog/shuttle لـ scrub فريم بفريم",
        "category": "playback",
        "params": {},
        "side_effects": ["playback_state"],
        "requires_confirmation": False,
    },
    "playback.set_aspect_ratio": {
        "description": "Set preview aspect ratio (9:16, 16:9, 1:1, 4:5)",
        "description_ar": "حدد أبعاد المعاينة (9:16, 16:9, 1:1, 4:5)",
        "category": "playback",
        "params": {"ratio": "string (9:16|16:9|1:1|4:5)"},
        "side_effects": ["preview_state"],
        "requires_confirmation": False,
    },
    "playback.set_fit_mode": {
        "description": "Set fit mode (fit=contain, fill=cover)",
        "description_ar": "حدد وضع الاحتواء (fit=contain, fill=cover)",
        "category": "playback",
        "params": {"mode": "string (fit|fill)"},
        "side_effects": ["preview_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_fullscreen": {
        "description": "Toggle fullscreen preview (F key)",
        "description_ar": "بدّل ملء الشاشة (مفتاح F)",
        "category": "playback",
        "params": {},
        "side_effects": ["window_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_mute": {
        "description": "Mute/unmute audio",
        "description_ar": "اكتم/شغّل الصوت",
        "category": "playback",
        "params": {},
        "side_effects": ["audio_state"],
        "requires_confirmation": False,
    },
    "playback.set_volume": {
        "description": "Set master volume (0-100)",
        "description_ar": "حدد مستوى الصوت (0-100)",
        "category": "playback",
        "params": {"volume": "float (0-100)"},
        "side_effects": ["audio_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_safe_area": {
        "description": "Toggle safe area guides (action/title safe)",
        "description_ar": "فعّل إرشادات الـ safe area",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.toggle_grid_overlay": {
        "description": "Toggle 3x3 grid overlay (rule of thirds)",
        "description_ar": "فعّل شبكة 3x3 (قاعدة الأثلاث)",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.set_timecode_format": {
        "description": "Set timecode format (DF/NDF, FPS)",
        "description_ar": "حدد صيغة الـ timecode (DF/NDF, FPS)",
        "category": "playback",
        "params": {"format": "string (df|ndf)", "fps": "integer"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "playback.toggle_waveform_overlay": {
        "description": "Toggle audio waveform overlay on canvas",
        "description_ar": "فعّل waveform صوتية على الكانفس",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.toggle_zebra": {
        "description": "Toggle zebra stripes (exposure warning)",
        "description_ar": "فعّل zebra stripes (تحذير exposure)",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.toggle_focus_peaking": {
        "description": "Toggle focus peaking (edge highlight)",
        "description_ar": "فعّل focus peaking (هايلايت الـ edges)",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.toggle_false_color": {
        "description": "Toggle false color (exposure aid)",
        "description_ar": "فعّل false color (مساعد exposure)",
        "category": "playback",
        "params": {},
        "side_effects": ["preview_overlay"],
        "requires_confirmation": False,
    },
    "playback.ab_compare": {
        "description": "Open A/B compare (two clips side by side)",
        "description_ar": "افتح A/B Compare (كليبين جنب بعض)",
        "category": "playback",
        "params": {"clip_a": "string", "clip_b": "string"},
        "side_effects": ["ui_state"],
        "requires_confirmation": False,
    },
    "playback.zoom_canvas": {
        "description": "Zoom into the canvas preview (pixel-level)",
        "description_ar": "زوّم في المعاينة (مستوى البكسل)",
        "category": "playback",
        "params": {"zoom": "float (1.0-10.0)"},
        "side_effects": ["preview_state"],
        "requires_confirmation": False,
    },
    "playback.eyedropper": {
        "description": "Pick a color from the preview frame",
        "description_ar": "قط لون من فريم المعاينة",
        "category": "playback",
        "params": {"x": "integer", "y": "integer"},
        "side_effects": ["color_picker"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 3. EFFECTS & COLOR (30 tools)
    # ════════════════════════════════════════════════════════════════════
    "effects.apply_lut": {
        "description": "Apply a LUT (.cube file) to selected clip",
        "description_ar": "طبّق LUT (ملف .cube) على الكليب",
        "category": "effects",
        "params": {"clip_id": "string", "lut_path": "string", "intensity": "float (0-1)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.remove_lut": {
        "description": "Remove LUT from selected clip",
        "description_ar": "شيل LUT من الكليب",
        "category": "effects",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_brightness": {
        "description": "Set brightness (-1 to 1)",
        "description_ar": "حدد السطوع (-1 إلى 1)",
        "category": "effects",
        "params": {"clip_id": "string", "brightness": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_contrast": {
        "description": "Set contrast (0 to 2)",
        "description_ar": "حدد التباين (0 إلى 2)",
        "category": "effects",
        "params": {"clip_id": "string", "contrast": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_saturation": {
        "description": "Set saturation (0 to 2)",
        "description_ar": "حدد التشبع (0 إلى 2)",
        "category": "effects",
        "params": {"clip_id": "string", "saturation": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_temperature": {
        "description": "Set color temperature (Kelvin)",
        "description_ar": "حدد حرارة اللون (Kelvin)",
        "category": "effects",
        "params": {"clip_id": "string", "temperature": "integer"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_exposure": {
        "description": "Set exposure (stops)",
        "description_ar": "حدد exposure (stops)",
        "category": "effects",
        "params": {"clip_id": "string", "exposure": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_curves": {
        "description": "Set RGB curves (parametric)",
        "description_ar": "حدد منحنيات RGB",
        "category": "effects",
        "params": {"clip_id": "string", "channel": "string (r|g|b|luma)", "points": "array"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.hsl_qualifier": {
        "description": "Isolate a color range (HSL secondary)",
        "description_ar": "اعزل مدى لون (HSL secondary)",
        "category": "effects",
        "params": {"clip_id": "string", "hue_center": "float", "hue_range": "float", "sat_range": "float", "lum_range": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_vignette": {
        "description": "Apply vignette effect",
        "description_ar": "طبّق تأثير vignette",
        "category": "effects",
        "params": {"clip_id": "string", "intensity": "float", "softness": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_film_grain": {
        "description": "Apply film grain",
        "description_ar": "طبّق film grain",
        "category": "effects",
        "params": {"clip_id": "string", "intensity": "float", "size": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_lens_distortion": {
        "description": "Apply lens distortion / barrel correction",
        "description_ar": "طبّق تشوّه العدسة / barrel correction",
        "category": "effects",
        "params": {"clip_id": "string", "k1": "float", "k2": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_sharpen": {
        "description": "Apply sharpen (unsharp mask)",
        "description_ar": "طبّق sharpen",
        "category": "effects",
        "params": {"clip_id": "string", "amount": "float", "radius": "float", "threshold": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_blur": {
        "description": "Apply Gaussian blur",
        "description_ar": "طبّق Gaussian blur",
        "category": "effects",
        "params": {"clip_id": "string", "radius": "float", "mask_path": "string (optional)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_motion_blur": {
        "description": "Apply directional motion blur",
        "description_ar": "طبّق motion blur اتجاهي",
        "category": "effects",
        "params": {"clip_id": "string", "direction_deg": "float", "amount": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_glow": {
        "description": "Apply glow / bloom effect",
        "description_ar": "طبّق glow / bloom",
        "category": "effects",
        "params": {"clip_id": "string", "intensity": "float", "threshold": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_chromatic_aberration": {
        "description": "Apply chromatic aberration",
        "description_ar": "طبّق chromatic aberration",
        "category": "effects",
        "params": {"clip_id": "string", "amount": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_lens_flare": {
        "description": "Add a lens flare overlay",
        "description_ar": "أضف lens flare",
        "category": "effects",
        "params": {"clip_id": "string", "preset": "string", "x": "float", "y": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_light_leak": {
        "description": "Apply light leak overlay",
        "description_ar": "طبّق light leak",
        "category": "effects",
        "params": {"clip_id": "string", "preset": "string", "intensity": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_pixelate": {
        "description": "Apply pixelate / mosaic effect",
        "description_ar": "طبّق pixelate / mosaic",
        "category": "effects",
        "params": {"clip_id": "string", "block_size": "integer"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_datamosh": {
        "description": "Apply datamosh glitch effect",
        "description_ar": "طبّق datamosh",
        "category": "effects",
        "params": {"clip_id": "string", "intensity": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_vhs": {
        "description": "Apply VHS / CRT effect",
        "description_ar": "طبّق تأثير VHS / CRT",
        "category": "effects",
        "params": {"clip_id": "string", "preset": "string", "intensity": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.apply_film_burn": {
        "description": "Apply film burn transition",
        "description_ar": "طبّق film burn",
        "category": "effects",
        "params": {"clip_id": "string", "intensity": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_blend_mode": {
        "description": "Set blend mode for an overlay clip",
        "description_ar": "حدد blend mode لكليب overlay",
        "category": "effects",
        "params": {"clip_id": "string", "blend_mode": "string (normal|multiply|screen|overlay|...)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_opacity": {
        "description": "Set clip opacity (0-1)",
        "description_ar": "حدد opacity الكليب (0-1)",
        "category": "effects",
        "params": {"clip_id": "string", "opacity": "float (0-1)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.add_opacity_keyframe": {
        "description": "Add opacity keyframe at a specific time",
        "description_ar": "أضف keyframe opacity في وقت معين",
        "category": "effects",
        "params": {"clip_id": "string", "time": "float", "value": "float", "easing": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.add_mask": {
        "description": "Add a mask (rect, ellipse, pen) to a clip",
        "description_ar": "أضف mask (مستطيل، بيضاوي، pen) لكليب",
        "category": "effects",
        "params": {"clip_id": "string", "shape": "string (rect|ellipse|pen)", "points": "array", "feather": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.warp_stabilize": {
        "description": "Warp stabilize (reduce camera shake)",
        "description_ar": "تثبيت عبر warp stabilizer",
        "category": "effects",
        "params": {"clip_id": "string", "smoothness": "float (0-1)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "effects.auto_color_match": {
        "description": "Match color between two clips",
        "description_ar": "طابق اللون بين كليبين",
        "category": "effects",
        "params": {"source_clip_id": "string", "target_clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_position_transform": {
        "description": "Set position, scale, rotation of a clip",
        "description_ar": "حدد الموضع، القياس، الدوران لكليب",
        "category": "effects",
        "params": {"clip_id": "string", "x": "float", "y": "float", "scale_x": "float", "scale_y": "float", "rotation": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.add_transform_keyframe": {
        "description": "Add transform keyframe (position/scale/rotation)",
        "description_ar": "أضف keyframe تحويل",
        "category": "effects",
        "params": {"clip_id": "string", "time": "float", "property": "string", "value": "any", "easing": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.set_crop": {
        "description": "Set crop (left, right, top, bottom percentages)",
        "description_ar": "حدد crop (يسار، يمين، فوق، تحت بالنسبة المئوية)",
        "category": "effects",
        "params": {"clip_id": "string", "left": "float", "right": "float", "top": "float", "bottom": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.reset_transform": {
        "description": "Reset all transforms on a clip",
        "description_ar": "صفر كل التحويلات على الكليب",
        "category": "effects",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.reset_color": {
        "description": "Reset all color grading on a clip",
        "description_ar": "صفر كل تدريج الألوان",
        "category": "effects",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "effects.copy_effects": {
        "description": "Copy effects from one clip to another",
        "description_ar": "انسخ التأثيرات من كليب لكليب",
        "category": "effects",
        "params": {"source_clip_id": "string", "target_clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 4. AUDIO (25 tools)
    # ════════════════════════════════════════════════════════════════════
    "audio.adjust_volume": {
        "description": "Adjust clip volume (0-2)",
        "description_ar": "اضبط صوت الكليب (0-2)",
        "category": "audio",
        "params": {"clip_id": "string", "volume": "float (0-2)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.set_fade_in": {
        "description": "Set fade-in duration",
        "description_ar": "حدد مدة fade-in",
        "category": "audio",
        "params": {"clip_id": "string", "duration_seconds": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.set_fade_out": {
        "description": "Set fade-out duration",
        "description_ar": "حدد مدة fade-out",
        "category": "audio",
        "params": {"clip_id": "string", "duration_seconds": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_eq": {
        "description": "Apply EQ (3-band or parametric)",
        "description_ar": "طبّق EQ (3-band أو parametric)",
        "category": "audio",
        "params": {"clip_id": "string", "low_gain": "float", "mid_gain": "float", "high_gain": "float", "low_freq": "float", "mid_freq": "float", "high_freq": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_compressor": {
        "description": "Apply audio compressor",
        "description_ar": "طبّق كومبريسور صوت",
        "category": "audio",
        "params": {"clip_id": "string", "threshold_db": "float", "ratio": "float", "attack_ms": "float", "release_ms": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_limiter": {
        "description": "Apply audio limiter (prevent clipping)",
        "description_ar": "طبّق limiter (منع clipping)",
        "category": "audio",
        "params": {"clip_id": "string", "ceiling_db": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_de_esser": {
        "description": "Apply de-esser (remove sibilance)",
        "description_ar": "طبّق de-esser (إزالة sibilance)",
        "category": "audio",
        "params": {"clip_id": "string", "frequency_hz": "float", "reduction_db": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_reverb": {
        "description": "Apply reverb send",
        "description_ar": "طبّق reverb send",
        "category": "audio",
        "params": {"clip_id": "string", "room_size": "float", "wetness": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.apply_delay": {
        "description": "Apply delay / echo",
        "description_ar": "طبّق delay / echo",
        "category": "audio",
        "params": {"clip_id": "string", "delay_ms": "float", "feedback": "float", "mix": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.normalize_loudness": {
        "description": "Normalize loudness to target LUFS",
        "description_ar": "طبّع مستوى الصوت لـ LUFS مستهدف",
        "category": "audio",
        "params": {"clip_id": "string", "target_lufs": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.auto_gain": {
        "description": "Auto-gain normalization",
        "description_ar": "تطبيع الكسب تلقائياً",
        "category": "audio",
        "params": {"clip_id": "string", "target_db": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.noise_reduction": {
        "description": "Apply noise reduction (profile-based)",
        "description_ar": "طبّق noise reduction (بروفايل)",
        "category": "audio",
        "params": {"clip_id": "string", "strength": "float (0-1)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.de_clip": {
        "description": "De-clip / de-crackle repair",
        "description_ar": "إصلاح de-clip / de-crackle",
        "category": "audio",
        "params": {"clip_id": "string", "threshold": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.voice_isolation": {
        "description": "Isolate vocals from background",
        "description_ar": "اعزل الصوت البشري عن الخلفية",
        "category": "audio",
        "params": {"clip_id": "string", "strength": "float (0-1)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "audio.vocal_clone": {
        "description": "Clone a voice from a sample (local model)",
        "description_ar": "انسخ صوت من عينة (نموذج محلي)",
        "category": "audio",
        "params": {"source_clip_id": "string", "target_text": "string", "output_path": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "audio.pitch_shift": {
        "description": "Pitch shift (±12 semitones)",
        "description_ar": "غيّر طبقة الصوت (±12 semitones)",
        "category": "audio",
        "params": {"clip_id": "string", "semitones": "float (-12 to 12)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.time_stretch": {
        "description": "Time-stretch audio (without pitch change)",
        "description_ar": "مدّد/أخصر الصوت (بدون تغيير طبقة)",
        "category": "audio",
        "params": {"clip_id": "string", "factor": "float (0.5-2.0)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.stereo_width": {
        "description": "Adjust stereo width",
        "description_ar": "عدّل عرض الستيريو",
        "category": "audio",
        "params": {"clip_id": "string", "width": "float (0-2)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.mono_merge": {
        "description": "Merge stereo to mono",
        "description_ar": "ادمج ستيريو لمونو",
        "category": "audio",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.phase_invert": {
        "description": "Invert phase",
        "description_ar": "اعكس الـ phase",
        "category": "audio",
        "params": {"clip_id": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.ducking": {
        "description": "Sidechain ducking (auto-lower music when speech)",
        "description_ar": "Sidechain ducking (تخفيض الموسيقى تلقائياً عند الكلام)",
        "category": "audio",
        "params": {"music_clip_id": "string", "speech_clip_id": "string", "attenuation_db": "float", "attack_ms": "float", "release_ms": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "audio.detect_beats": {
        "description": "Detect beats and return BPM + timestamps",
        "description_ar": "اكتشف الـ beats وارجع BPM + الأوقات",
        "category": "audio",
        "params": {"clip_id": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "audio.detect_key": {
        "description": "Detect musical key of audio",
        "description_ar": "اكتشف الـ musical key للصوت",
        "category": "audio",
        "params": {"clip_id": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "audio.separate_stems": {
        "description": "Separate audio into stems (vocals/drums/bass/other)",
        "description_ar": "افصل الصوت لـ stems (vocals/drums/bass/other)",
        "category": "audio",
        "params": {"clip_id": "string", "output_dir": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": False,
    },
    "audio.apply_crossfade": {
        "description": "Apply audio crossfade preset between two clips",
        "description_ar": "طبّق crossfade صوتي بين كليبين",
        "category": "audio",
        "params": {"clip_a_id": "string", "clip_b_id": "string", "preset": "string", "duration_seconds": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 5. SUBTITLES (22 tools)
    # ════════════════════════════════════════════════════════════════════
    "subtitles.generate_from_audio": {
        "description": "Transcribe audio to subtitles (Whisper)",
        "description_ar": "حوّل الصوت لترجمات (Whisper)",
        "category": "subtitles",
        "params": {"language": "string (auto|ar|en|...)", "model": "string (tiny|base|small|medium|large)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "subtitles.translate": {
        "description": "Translate subtitles to target language",
        "description_ar": "ترجم الترجمات للغة المستهدفة",
        "category": "subtitles",
        "params": {"target_language": "string", "source_language": "string (auto)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "subtitles.add_subtitle": {
        "description": "Add a single subtitle clip",
        "description_ar": "أضف ترجمة واحدة",
        "category": "subtitles",
        "params": {"text": "string", "start_time": "float", "end_time": "float", "style": "object"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.delete_subtitle": {
        "description": "Delete a subtitle clip",
        "description_ar": "احذف ترجمة",
        "category": "subtitles",
        "params": {"subtitle_id": "string"},
        "side_effects": ["timeline_state", "undo_stack"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "subtitles.update_text": {
        "description": "Update subtitle text",
        "description_ar": "عدّل نص الترجمة",
        "category": "subtitles",
        "params": {"subtitle_id": "string", "text": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.update_timing": {
        "description": "Update subtitle timing (start/end)",
        "description_ar": "عدّل توقيت الترجمة (بداية/نهاية)",
        "category": "subtitles",
        "params": {"subtitle_id": "string", "start_time": "float", "end_time": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.nudge_timing": {
        "description": "Nudge all subtitles by offset (ms)",
        "description_ar": "حرّك كل الترجمات بإزاحة (ms)",
        "category": "subtitles",
        "params": {"offset_ms": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.apply_style": {
        "description": "Apply a subtitle style (font, color, animation)",
        "description_ar": "طبّق style على الترجمة",
        "category": "subtitles",
        "params": {"subtitle_id": "string | all", "style": "object (SubtitleClipStyle)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.apply_template": {
        "description": "Apply a subtitle template (TikTok/YouTube/IG)",
        "description_ar": "طبّق قالب ترجمة (TikTok/YouTube/IG)",
        "category": "subtitles",
        "params": {"template": "string (tiktok_youtube|instagram|...)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.search_replace": {
        "description": "Search and replace in all subtitles",
        "description_ar": "ابحث واستبدل في كل الترجمات",
        "category": "subtitles",
        "params": {"search": "string", "replace": "string", "case_sensitive": "boolean"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.toggle_burn_in": {
        "description": "Toggle burn-in (embedded vs soft)",
        "description_ar": "بدّل burn-in (مدمجة أو ناعمة)",
        "category": "subtitles",
        "params": {"burned": "boolean"},
        "side_effects": ["render_state"],
        "requires_confirmation": False,
    },
    "subtitles.toggle_karaoke": {
        "description": "Toggle karaoke mode (word-by-word highlight)",
        "description_ar": "بدّل وضع karaoke (هايلايت كلمة بكلمة)",
        "category": "subtitles",
        "params": {"enabled": "boolean"},
        "side_effects": ["render_state"],
        "requires_confirmation": False,
    },
    "subtitles.set_animation": {
        "description": "Set subtitle animation (pop_in/typewriter/fade/...)",
        "description_ar": "حدد حركة الترجمة",
        "category": "subtitles",
        "params": {"subtitle_id": "string | all", "animation": "string (pop_in|typewriter|fade|...)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.set_alignment": {
        "description": "Set subtitle alignment (8 positions)",
        "description_ar": "حدد مكان الترجمة (8 مواقع)",
        "category": "subtitles",
        "params": {"subtitle_id": "string | all", "alignment": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.import_srt": {
        "description": "Import subtitles from SRT file",
        "description_ar": "استورد ترجمات من ملف SRT",
        "category": "subtitles",
        "params": {"file_path": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.import_vtt": {
        "description": "Import subtitles from VTT file",
        "description_ar": "استورد ترجمات من ملف VTT",
        "category": "subtitles",
        "params": {"file_path": "string"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.export_srt": {
        "description": "Export subtitles as SRT",
        "description_ar": "صدّر الترجمات كـ SRT",
        "category": "subtitles",
        "params": {"file_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": False,
    },
    "subtitles.auto_punctuate": {
        "description": "Auto-add punctuation to subtitles",
        "description_ar": "أضف علامات ترقيم تلقائياً",
        "category": "subtitles",
        "params": {},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.auto_line_break": {
        "description": "Auto-line break subtitles by max length",
        "description_ar": "كسّر الترجمات تلقائياً حسب الطول",
        "category": "subtitles",
        "params": {"max_chars": "integer"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.diarize_speakers": {
        "description": "Speaker diarization (label Speaker 1, 2, ...)",
        "description_ar": "وسم المتحدثين (Speaker 1, 2, ...)",
        "category": "subtitles",
        "params": {"num_speakers": "integer (auto)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "subtitles.censor_profanity": {
        "description": "Censor profanity (mute beep or black box)",
        "description_ar": "احجب الكلمات البذيئة (beep أو مربع أسود)",
        "category": "subtitles",
        "params": {"method": "string (beep|box|censor)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "subtitles.live_caption": {
        "description": "Start live captioning (real-time filler word detection)",
        "description_ar": "ابدأ live captioning (كشف filler words فوري)",
        "category": "subtitles",
        "params": {},
        "side_effects": ["live_session", "long_running"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 6. AI & ML (45 tools) — these are all already AI features
    # ════════════════════════════════════════════════════════════════════
    "ai.auto_cut_silences": {
        "description": "Auto-detect and remove silences",
        "description_ar": "اكتشف واحذف الصمت تلقائياً",
        "category": "ai",
        "params": {"threshold_db": "float", "min_duration": "float"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.auto_framing": {
        "description": "Auto-frame (track faces, recompose)",
        "description_ar": "Auto-framing (تتبع الوجوه، إعادة تأطير)",
        "category": "ai",
        "params": {"target_aspect": "string (9:16|1:1|16:9)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.beat_sync": {
        "description": "Sync B-rolls to beat timestamps",
        "description_ar": "زامن الـ B-rolls مع الإيقاع",
        "category": "ai",
        "params": {"broll_track_id": "string", "music_clip_id": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.smart_recut": {
        "description": "Smart re-cut for podcasts (remove filler words, tighten)",
        "description_ar": "مونتاج ذكي للـ podcasts (احذف filler، شدّد)",
        "category": "ai",
        "params": {"filler_removal": "boolean", "tighten_factor": "float (0-1)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.remove_filler_words": {
        "description": "Remove filler words (um, uh, like)",
        "description_ar": "احذف filler words (um, uh, like)",
        "category": "ai",
        "params": {"language": "string (auto|ar|en)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.jump_cut_remover": {
        "description": "Remove jump cuts (smooth single-speaker edits)",
        "description_ar": "احذف الـ jump cuts (تنعيم مقاطع متحدث واحد)",
        "category": "ai",
        "params": {"max_gap_seconds": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.auto_zoom_speech": {
        "description": "Auto-zoom on speech emphasis (He-Man style)",
        "description_ar": "زوّم تلقائي على تأكيدات الكلام",
        "category": "ai",
        "params": {"zoom_factor": "float (1.0-1.5)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "ai.auto_crop_social": {
        "description": "Auto-crop for social (9:16, 1:1, 4:5)",
        "description_ar": "قص تلقائي للسوشيال (9:16, 1:1, 4:5)",
        "category": "ai",
        "params": {"target_aspect": "string (9:16|1:1|4:5)"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "ai.lip_sync_translation": {
        "description": "Lip-sync to translated audio (Wav2Lip)",
        "description_ar": "زامن حركة الشفاه مع الترجمة (Wav2Lip)",
        "category": "ai",
        "params": {"target_language": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.deepfake_detector": {
        "description": "Detect deepfakes / synthetic media",
        "description_ar": "اكتشف deepfakes / وسائط مولّدة",
        "category": "ai",
        "params": {"clip_id": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.generate_thumbnail": {
        "description": "Generate thumbnail from best frame + title",
        "description_ar": "ولّد thumbnail من أحسن فريم + عنوان",
        "category": "ai",
        "params": {"style": "string (bold|clean|curious)", "output_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": False,
    },
    "ai.generate_title": {
        "description": "Generate video title (Arabic or English)",
        "description_ar": "ولّد عنوان الفيديو (عربي أو إنجليزي)",
        "category": "ai",
        "params": {"count": "integer", "language": "string", "tone": "string (curious|bold|informative)"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.generate_description": {
        "description": "Generate video description",
        "description_ar": "ولّد وصف الفيديو",
        "category": "ai",
        "params": {"language": "string", "include_timestamps": "boolean"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.suggest_hashtags": {
        "description": "Suggest hashtags",
        "description_ar": "اقترح هاشتاجات",
        "category": "ai",
        "params": {"count": "integer", "platform": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.score_virality": {
        "description": "Score virality of timeline",
        "description_ar": "احسب الـ virality للتايملاين",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.predict_engagement": {
        "description": "Predict engagement (views, retention)",
        "description_ar": "توقّع التفاعل (مشاهدات، retention)",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.check_copyright": {
        "description": "Check for copyright issues (audio fingerprint)",
        "description_ar": "تحقق من حقوق الملكية (audio fingerprint)",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.predict_trend": {
        "description": "Predict trend relevance",
        "description_ar": "توقّع صلة الترند",
        "category": "ai",
        "params": {"trend_topic": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.match_audience": {
        "description": "Match content to target audience",
        "description_ar": "طابق المحتوى للجمهور المستهدف",
        "category": "ai",
        "params": {"audience_description": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.suggest_posting_time": {
        "description": "Suggest best posting time (per platform)",
        "description_ar": "اقترح أفضل وقت للنشر (لكل منصة)",
        "category": "ai",
        "params": {"platform": "string", "timezone": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.analyze_competitors": {
        "description": "Analyze competitor content",
        "description_ar": "حلّل محتوى المنافسين",
        "category": "ai",
        "params": {"competitor_handles": "array of strings"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.detect_emotion": {
        "description": "Detect emotion in face/voice",
        "description_ar": "اكتشف المشاعر في الوجه/الصوت",
        "category": "ai",
        "params": {"clip_id": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.analyze_pacing": {
        "description": "Analyze video pacing (cuts per minute)",
        "description_ar": "حلّل إيقاع الفيديو (قطعات/دقيقة)",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.detect_chapters": {
        "description": "Auto-detect chapters (split by topic)",
        "description_ar": "اكتشف فصول تلقائياً (قسّم حسب الموضوع)",
        "category": "ai",
        "params": {"min_chapter_duration": "float"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.generate_highlight_reel": {
        "description": "Auto-curate highlight reel (best moments)",
        "description_ar": "ولّد highlight reel (أحسن اللحظات)",
        "category": "ai",
        "params": {"target_duration": "float", "count": "integer"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.remove_background": {
        "description": "Remove background (RMBG-1.4)",
        "description_ar": "احذف الخلفية",
        "category": "ai",
        "params": {"clip_id": "string", "method": "string (rmbg|sam|chromakey)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.detect_scenes": {
        "description": "Auto-detect scenes (split by cuts)",
        "description_ar": "اكتشف المشاهد تلقائياً",
        "category": "ai",
        "params": {"threshold": "float (0-1)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.remove_object": {
        "description": "Remove object (inpainting)",
        "description_ar": "احذف كائن (inpainting)",
        "category": "ai",
        "params": {"clip_id": "string", "object_mask": "string (path or coords)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.color_match": {
        "description": "Auto color match between clips",
        "description_ar": "طابق اللون تلقائياً بين كليبات",
        "category": "ai",
        "params": {"source_clip_id": "string", "target_clip_id": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.style_transfer": {
        "description": "Apply style transfer (Van Gogh, anime, ...)",
        "description_ar": "طبّق style transfer (Van Gogh, anime)",
        "category": "ai",
        "params": {"clip_id": "string", "style": "string (vangogh|anime|...)", "intensity": "float"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.upscale_video": {
        "description": "Upscale video (4K super-resolution)",
        "description_ar": "زوّد دقة الفيديو (4K super-resolution)",
        "category": "ai",
        "params": {"clip_id": "string", "target_resolution": "string (1080p|4k)"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.interpolate_frames": {
        "description": "Frame interpolation (60fps from 30fps)",
        "description_ar": "Frame interpolation (60fps من 30fps)",
        "category": "ai",
        "params": {"clip_id": "string", "target_fps": "integer"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.denoise_video": {
        "description": "AI denoise video",
        "description_ar": "إزالة الضوضاء من الفيديو",
        "category": "ai",
        "params": {"clip_id": "string", "strength": "float"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.suggest_transitions": {
        "description": "Suggest transitions between clips",
        "description_ar": "اقترح انتقالات بين الكليبات",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.suggest_sound_design": {
        "description": "Suggest SFX from text description",
        "description_ar": "اقترح مؤثرات صوتية من وصف نصي",
        "category": "ai",
        "params": {"description": "string", "time": "float"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.generate_voiceover": {
        "description": "Generate voiceover (TTS)",
        "description_ar": "ولّد voiceover (TTS)",
        "category": "ai",
        "params": {"text": "string", "voice": "string", "language": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.generate_narration": {
        "description": "Generate narration for a clip",
        "description_ar": "ولّد narration لكليب",
        "category": "ai",
        "params": {"clip_id": "string", "tone": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": False,
    },
    "ai.analyze_story_arc": {
        "description": "Analyze story arc of video",
        "description_ar": "حلّل القوس الدرامي للفيديو",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.generate_hooks_v2": {
        "description": "Generate 3 viral hook variants (A/B test)",
        "description_ar": "ولّد 3 نسخ viral hook (A/B test)",
        "category": "ai",
        "params": {"count": "integer", "tone": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.suggest_brolls": {
        "description": "Suggest B-rolls for a clip",
        "description_ar": "اقترح B-rolls لكليب",
        "category": "ai",
        "params": {"clip_id": "string", "count": "integer"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.content_rating": {
        "description": "Auto-rate content (G/PG/PG-13/R)",
        "description_ar": "تقييم المحتوى تلقائياً (G/PG/PG-13/R)",
        "category": "ai",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "ai.local_llm_toggle": {
        "description": "Toggle local LLM (Ollama) instead of cloud",
        "description_ar": "بدّل LLM محلي (Ollama) بدل الـ cloud",
        "category": "ai",
        "params": {"enabled": "boolean", "model": "string"},
        "side_effects": ["ai_config"],
        "requires_confirmation": False,
    },
    "ai.scene_captioning": {
        "description": "Generate scene descriptions (visual captioning)",
        "description_ar": "ولّد أوصاف المشاهد (visual captioning)",
        "category": "ai",
        "params": {"clip_id": "string", "interval_seconds": "float"},
        "side_effects": ["metadata", "long_running"],
        "requires_confirmation": False,
    },
    "ai.macro_record": {
        "description": "Record current AI actions as a macro",
        "description_ar": "سجّل إجراءات الـ AI الحالية كـ macro",
        "category": "ai",
        "params": {"macro_name": "string"},
        "side_effects": ["macros"],
        "requires_confirmation": False,
    },
    "ai.macro_play": {
        "description": "Play a saved macro",
        "description_ar": "شغّل macro محفوظ",
        "category": "ai",
        "params": {"macro_id": "string"},
        "side_effects": ["timeline_state", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "ai.search_stock": {
        "description": "Search stock media (Pexels/Pixabay/Freesound)",
        "description_ar": "ابحث في stock media (Pexels/Pixabay/Freesound)",
        "category": "ai",
        "params": {"query": "string", "type": "string (video|image|audio)", "engine": "string"},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },

    # ════════════════════════════════════════════════════════════════════
    # 7. EXPORT (25 tools)
    # ════════════════════════════════════════════════════════════════════
    "export.render": {
        "description": "Render timeline to video file",
        "description_ar": "صدّر التايملاين كملف فيديو",
        "category": "export",
        "params": {"output_path": "string", "preset": "string", "resolution": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.render_proxy": {
        "description": "Render proxy (low-res) for smooth editing",
        "description_ar": "صدّر proxy (دقة منخفضة) للمونتاج السلس",
        "category": "export",
        "params": {"clip_id": "string", "resolution": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": False,
    },
    "export.export_xml_resolve": {
        "description": "Export as DaVinci Resolve XML",
        "description_ar": "صدّر كـ XML لـ DaVinci Resolve",
        "category": "export",
        "params": {"file_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_xml_premiere": {
        "description": "Export as Premiere Pro XML",
        "description_ar": "صدّر كـ XML لـ Premiere Pro",
        "category": "export",
        "params": {"file_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_xml_final_cut": {
        "description": "Export as Final Cut Pro XML",
        "description_ar": "صدّر كـ XML لـ Final Cut",
        "category": "export",
        "params": {"file_path": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_aaf": {
        "description": "Export as AAF/OMF (Pro Tools)",
        "description_ar": "صدّر كـ AAF/OMF (Pro Tools)",
        "category": "export",
        "params": {"file_path": "string", "format": "string (aaf|omf)"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_gif": {
        "description": "Export as GIF (looping preview)",
        "description_ar": "صدّر كـ GIF (معاينة بـ loop)",
        "category": "export",
        "params": {"file_path": "string", "loop": "boolean"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_audio": {
        "description": "Export audio only (mp3/m4a/wav)",
        "description_ar": "صدّر الصوت بس (mp3/m4a/wav)",
        "category": "export",
        "params": {"file_path": "string", "format": "string"},
        "side_effects": ["filesystem"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_prores": {
        "description": "Export as ProRes (mastering)",
        "description_ar": "صدّر كـ ProRes (mastering)",
        "category": "export",
        "params": {"file_path": "string", "variant": "string (proxy|lt|422|4444)"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_h265": {
        "description": "Export as H.265/HEVC",
        "description_ar": "صدّر كـ H.265/HEVC",
        "category": "export",
        "params": {"file_path": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_hdr": {
        "description": "Export as HDR (HDR10, Dolby Vision)",
        "description_ar": "صدّر كـ HDR (HDR10, Dolby Vision)",
        "category": "export",
        "params": {"file_path": "string", "hdr_format": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.upload_youtube": {
        "description": "Upload to YouTube (OAuth required)",
        "description_ar": "ارفع على YouTube (OAuth)",
        "category": "export",
        "params": {"title": "string", "description": "string", "tags": "array", "privacy": "string"},
        "side_effects": ["network", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.upload_tiktok": {
        "description": "Upload to TikTok",
        "description_ar": "ارفع على TikTok",
        "category": "export",
        "params": {"caption": "string", "hashtags": "array"},
        "side_effects": ["network", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.upload_instagram": {
        "description": "Upload to Instagram Reels",
        "description_ar": "ارفع على Instagram Reels",
        "category": "export",
        "params": {"caption": "string", "hashtags": "array"},
        "side_effects": ["network", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.upload_youtube_shorts": {
        "description": "Upload to YouTube Shorts",
        "description_ar": "ارفع على YouTube Shorts",
        "category": "export",
        "params": {"title": "string", "description": "string"},
        "side_effects": ["network", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.create_share_link": {
        "description": "Create a shareable preview link",
        "description_ar": "اعمل لينك معاينة للمشاركة",
        "category": "export",
        "params": {"expiry_hours": "integer"},
        "side_effects": ["network"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.apply_watermark": {
        "description": "Apply watermark (image/text overlay)",
        "description_ar": "طبّق علامة مائية",
        "category": "export",
        "params": {"image_path": "string", "position": "string", "opacity": "float"},
        "side_effects": ["timeline_state"],
        "requires_confirmation": False,
    },
    "export.batch_render": {
        "description": "Batch render multiple timelines",
        "description_ar": "صدّر عدة تايملاينز دفعة واحدة",
        "category": "export",
        "params": {"timeline_ids": "array", "output_dir": "string"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.export_per_platform": {
        "description": "Export variants for each platform (TikTok/YT/IG)",
        "description_ar": "صدّر نسخ لكل منصة (TikTok/YT/IG)",
        "category": "export",
        "params": {"output_dir": "string", "platforms": "array"},
        "side_effects": ["filesystem", "long_running"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.add_chapter_markers": {
        "description": "Add chapter markers in export",
        "description_ar": "أضف chapter markers في التصدير",
        "category": "export",
        "params": {"enabled": "boolean"},
        "side_effects": ["export_state"],
        "requires_confirmation": False,
    },
    "export.embed_metadata": {
        "description": "Embed EXIF/IPTC metadata in export",
        "description_ar": "ادمج EXIF/IPTC metadata في التصدير",
        "category": "export",
        "params": {"metadata": "object"},
        "side_effects": ["export_state"],
        "requires_confirmation": False,
    },
    "export.queue_add": {
        "description": "Add a render job to the queue",
        "description_ar": "أضف job render للطابور",
        "category": "export",
        "params": {"job": "object"},
        "side_effects": ["queue_state"],
        "requires_confirmation": False,
    },
    "export.queue_status": {
        "description": "Get render queue status",
        "description_ar": "اعرف حالة طابور الرندر",
        "category": "export",
        "params": {},
        "side_effects": ["metadata"],
        "requires_confirmation": False,
    },
    "export.cancel_job": {
        "description": "Cancel a queued/running render job",
        "description_ar": "ألغِ job render في الطابور",
        "category": "export",
        "params": {"job_id": "string"},
        "side_effects": ["queue_state"],
        "requires_confirmation": True,
        "destructive": True,
    },
    "export.background_render": {
        "description": "Start background render (non-blocking)",
        "description_ar": "ابدأ رندر في الخلفية",
        "category": "export",
        "params": {"output_path": "string"},
        "side_effects": ["background_task"],
        "requires_confirmation": False,
    },
    "export.share_review_link": {
        "description": "Share a review link with comments enabled",
        "description_ar": "شارك لينك مراجعة مع تعليقات",
        "category": "export",
        "params": {"expiry_hours": "integer", "allow_comments": "boolean"},
        "side_effects": ["network"],
        "requires_confirmation": True,
        "destructive": True,
    },
}


# ─────────────────────────────────────────────────────────────────────────────
# Whitelist configuration (trusted actions that don't need confirmation)
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_WHITELIST = {
    "trusted": [
        "timeline.split_clip",
        "timeline.razor_at_playhead",
        "timeline.three_point_edit",
        "timeline.slip_clip",
        "timeline.slide_clip",
        "timeline.freeze_frame",
        "timeline.reverse_clip",
        "timeline.time_remap",
        "timeline.mark_in_out",
        "timeline.add_marker",
        "timeline.add_chapter_marker",
        "timeline.set_region_of_interest",
        "timeline.take_snapshot",
        "timeline.group_clips",
        "timeline.ungroup_clips",
        "playback.play",
        "playback.pause",
        "playback.toggle_play",
        "playback.seek",
        "playback.frame_step_forward",
        "playback.frame_step_backward",
        "playback.skip_forward_5s",
        "playback.skip_backward_5s",
        "playback.toggle_loop",
        "playback.set_aspect_ratio",
        "playback.set_fit_mode",
        "playback.toggle_fullscreen",
        "playback.toggle_mute",
        "playback.set_volume",
        "playback.toggle_safe_area",
        "playback.toggle_grid_overlay",
        "playback.toggle_waveform_overlay",
        "playback.toggle_zebra",
        "playback.toggle_focus_peaking",
        "playback.toggle_false_color",
        "playback.zoom_canvas",
        "playback.eyedropper",
        "playback.ab_compare",
        "effects.*",  # All effect operations are trusted
        "audio.adjust_volume",
        "audio.set_fade_in",
        "audio.set_fade_out",
        "audio.*",  # All audio adjustments are trusted
        "subtitles.add_subtitle",
        "subtitles.update_text",
        "subtitles.update_timing",
        "subtitles.nudge_timing",
        "subtitles.apply_style",
        "subtitles.apply_template",
        "subtitles.search_replace",
        "subtitles.set_animation",
        "subtitles.set_alignment",
        "subtitles.auto_punctuate",
        "subtitles.auto_line_break",
        "subtitles.toggle_burn_in",
        "subtitles.toggle_karaoke",
        "subtitles.*",  # All subtitle adjustments (except delete) are trusted
        "ai.auto_zoom_speech",
        "ai.auto_crop_social",
        "ai.suggest_transitions",
        "ai.detect_emotion",
        "ai.analyze_pacing",
        "ai.score_virality",
        "ai.predict_engagement",
        "ai.content_rating",
        "ai.*",  # Most AI queries are trusted
    ],
    "always_confirm": [
        "timeline.delete_clip",
        "timeline.ripple_delete",
        "timeline.replace_clip",
        "timeline.lift_clip",
        "timeline.extract_clip",
        "ai.auto_cut_silences",
        "ai.smart_recut",
        "ai.remove_filler_words",
        "ai.jump_cut_remover",
        "ai.generate_highlight_reel",
        "ai.remove_object",
        "ai.upscale_video",
        "ai.macro_play",
        "audio.vocal_clone",
        "export.*",  # All exports require confirmation
        "subtitles.delete_subtitle",
    ],
}


# ─────────────────────────────────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────────────────────────────────

def get_tool(name: str) -> Optional[Dict[str, Any]]:
    """Get a tool by name. Returns None if not found."""
    return TOOL_REGISTRY.get(name)


def list_tools_by_category(category: str) -> List[str]:
    """List all tool names in a category."""
    return [name for name, tool in TOOL_REGISTRY.items() if tool.get("category") == category]


def list_all_tools() -> List[str]:
    """List all tool names."""
    return list(TOOL_REGISTRY.keys())


def is_trusted(tool_name: str, whitelist: Dict[str, List[str]] = None) -> bool:
    """Check if a tool is in the user's whitelist (trusted)."""
    wl = whitelist or DEFAULT_WHITELIST
    trusted = wl.get("trusted", [])
    always_confirm = wl.get("always_confirm", [])

    # Always-confirm overrides
    for pattern in always_confirm:
        if pattern.endswith("*"):
            if tool_name.startswith(pattern[:-1]):
                return False
        elif pattern == tool_name:
            return False

    # Check trusted
    for pattern in trusted:
        if pattern.endswith("*"):
            if tool_name.startswith(pattern[:-1]):
                return True
        elif pattern == tool_name:
            return True

    return False


def needs_confirmation(tool_name: str, whitelist: Dict[str, List[str]] = None) -> bool:
    """Check if a tool needs user confirmation."""
    tool = get_tool(tool_name)
    if not tool:
        return True  # Unknown tools always need confirmation
    if is_trusted(tool_name, whitelist):
        return False
    return tool.get("requires_confirmation", False)


def get_tool_summary_for_llm() -> str:
    """Generate a compact tool summary string for the LLM prompt."""
    lines = []
    for category, label in TOOL_CATEGORIES.items():
        tools = list_tools_by_category(category)
        lines.append(f"\n## {label}")
        for name in tools:
            tool = TOOL_REGISTRY[name]
            desc = tool.get("description_ar") or tool.get("description", "")
            lines.append(f"- `{name}`: {desc}")
    return "\n".join(lines)


def get_tool_schema_for_llm(name: str) -> Optional[Dict[str, Any]]:
    """Get tool schema formatted for LLM function-calling."""
    tool = get_tool(name)
    if not tool:
        return None
    return {
        "name": name,
        "description": tool.get("description_ar", tool.get("description", "")),
        "parameters": {
            "type": "object",
            "properties": {
                k: {"type": "string", "description": v} if isinstance(v, str) else v
                for k, v in tool.get("params", {}).items()
            },
            "required": list(tool.get("params", {}).keys()),
        },
    }


def get_function_calling_specs() -> List[Dict[str, Any]]:
    """Get all tool specs in OpenAI/Gemini function-calling format."""
    return [get_tool_schema_for_llm(name) for name in TOOL_REGISTRY.keys()]


# Count
def count_tools() -> int:
    return len(TOOL_REGISTRY)


if __name__ == "__main__":
    print(f"Total tools registered: {count_tools()}")
    for category, label in TOOL_CATEGORIES.items():
        tools = list_tools_by_category(category)
        print(f"  {label}: {len(tools)} tools")
