include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: false
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    prefer_const_literals_to_create_immutables: true
    use_super_parameters: true
    avoid_unnecessary_containers: true
    sort_child_properties_last: true
    prefer_const_constructors_in_immutables: true
    require_trailing_commas: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
